# Item table configuration
[table]
seperate_columns = true # Whether to put a seperating character between columns
seperate_rows = false # Whether to put a seperating character between rows

# Characters to use when formating item tables
[table.characters]
horizontal = "─"
vertical = "│"
up_horizontal = "┴"
down_horizontal = "┬"
vertical_right = "├"
vertical_left = "┤"
vertical_horizontal = "┼"
down_right = "┌"
down_left = "┐"
up_right = "└"
up_left = "┘"
